driver:
	javac Main.java AbstractFactory.java Battery.java Camera.java Case.java CPURAM.java Display.java EUBattery.java EUCamera.java EUCase.java EUCPURAM.java EUDisplay.java EUFactory.java EUStorage.java EUStore.java GlobalBattery.java GlobalCamera.java GlobalCase.java GlobalCPURAM.java GlobalDisplay.java GlobalFactory.java GlobalStorage.java GlobalStore.java IflasDeluxe.java IIAmanIflas.java MaximumEffort.java Phone.java Storage.java Store.java TurkeyBattery.java TurkeyCamera.java TurkeyCase.java TurkeyCPURAM.java TurkeyDisplay.java TurkeyFactory.java TurkeyStorage.java TurkeyStore.java

run:
	java Main
clean:
	rm *class
